### ISSUE TITLE
Ubuntu install script failing on new 14.04

### ISSUE THREAD

**Issue by chrxr** [torchbox/wagtaildemo#37]
Running the Ubuntu one-liner on a new, clean Ubuntu 14.04 box with Digital Ocean.
(curl -O https://wagtail.io/ubuntu.sh; bash ubuntu.sh)

Script gets all the way through, but can't access Wagtail demo at the IP when finished.

Looking back through the messages in the terminal, seems to be an error at createdb stage, "Peer authentication failed for user 'postgres'"

See below:

    Cleaning up...
    swapoff on /tmpswap
    createdb: could not connect to database template1: FATAL:  Peer authentication failed for user "postgres"
    Syncing...
    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
      execute_from_command_line(sys.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
      utility.execute()
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
      self.execute(*args, **options.__dict__)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
      output = self.handle(*args, **options)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
      return self.handle_noargs(**options)
    File "/usr/local/lib/python2.7/dist-packages/south/management/commands/syncdb.py", line 92, in handle_noargs
      syncdb.Command().execute(**options)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
      output = self.handle(*args, **options)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 415, in handle
      return self.handle_noargs(**options)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/syncdb.py", line 57, in handle_noargs
      cursor = connection.cursor()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 162, in cursor
      cursor = util.CursorWrapper(self._cursor(), self)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 132, in _cursor
      self.ensure_connection()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
      six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 115, in connect
      self.connection = self.get_new_connection(conn_params)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 114, in get_new_connection
      return Database.connect(**conn_params)
    File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
      conn = _connect(dsn, connection_factory=connection_factory, async=async)
    django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "postgres"

    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
      execute_from_command_line(sys.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
      utility.execute()
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
      self.execute(*args, **options.__dict__)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
      output = self.handle(*args, **options)
    File "/usr/local/lib/python2.7/dist-packages/south/management/commands/migrate.py", line 111, in handle
      ignore_ghosts = ignore_ghosts,
    File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 200, in migrate_app
      applied_all = check_migration_histories(applied_all, delete_ghosts, ignore_ghosts)
    File "/usr/local/lib/python2.7/dist-packages/south/migration/__init__.py", line 79, in check_migration_histories
      for h in histories:
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 96, in __iter__
      self._fetch_all()
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
      self._result_cache = list(self.iterator())
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
      for row in compiler.results_iter():
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
      for rows in self.execute_sql(MULTI):
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
      cursor = self.connection.cursor()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 162, in cursor
      cursor = util.CursorWrapper(self._cursor(), self)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 132, in _cursor
      self.ensure_connection()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
      six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 115, in connect
      self.connection = self.get_new_connection(conn_params)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 114, in get_new_connection
      return Database.connect(**conn_params)
    File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
      conn = _connect(dsn, connection_factory=connection_factory, async=async)
    django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "postgres"

    Getting object list
    Traceback (most recent call last):
    File "./manage.py", line 10, in <module>
      execute_from_command_line(sys.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
      utility.execute()
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 392, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 242, in run_from_argv
      self.execute(*args, **options.__dict__)
    File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 285, in execute
      output = self.handle(*args, **options)
    File "/usr/local/lib/python2.7/dist-packages/wagtail/wagtailsearch/management/commands/update_index.py", line 27, in handle
      for obj in model.get_indexed_objects():
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 96, in __iter__
      self._fetch_all()
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 857, in _fetch_all
      self._result_cache = list(self.iterator())
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 220, in iterator
      for row in compiler.results_iter():
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 713, in results_iter
      for rows in self.execute_sql(MULTI):
    File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 785, in execute_sql
      cursor = self.connection.cursor()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 162, in cursor
      cursor = util.CursorWrapper(self._cursor(), self)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 132, in _cursor
      self.ensure_connection()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 99, in __exit__
      six.reraise(dj_exc_type, dj_exc_value, traceback)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 127, in ensure_connection
      self.connect()
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/__init__.py", line 115, in connect
      self.connection = self.get_new_connection(conn_params)
    File "/usr/local/lib/python2.7/dist-packages/django/db/backends/postgresql_psycopg2/base.py", line 114, in get_new_connection
      return Database.connect(**conn_params)
    File "/usr/local/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
      conn = _connect(dsn, connection_factory=connection_factory, async=async)
    django.db.utils.OperationalError: FATAL:  Peer authentication failed for user "postgres"

**Comment by gasman** [comment]
Presumably this is now fixed for 14.04, by https://github.com/torchbox/wagtail/commit/4b79f3c428f28aabbf5c712209dae11c4eec28a6 ?

**Comment by gasman** [comment]
Closing as these scripts are no longer supported.
