### ISSUE TITLE
vagrant up fails

### ISSUE THREAD

**Issue by alexhayes** [torchbox/wagtaildemo#69]
Following the instructions [outlined in the docs](http://docs.wagtail.io/en/latest/getting_started/using_vagrant.html) the current demo fails on `vagrant up` as follows;

```
$ vagrant up
...
...
...
==> default: Successfully installed Django-1.7.8 Pillow-2.8.1 South-1.0 Unidecode-0.4.17 beautifulsoup4-4.3.2 dj-database-url-0.3.0 dj-static-0.0.6 django-appconf-1.0.1 django-compressor-1.5 django-libsass-0.3 django-modelcluster-0.6.2 django-taggit-0.14.0 django-treebeard-2.0 gunicorn-19.1.1 html5lib-0.999 libsass-0.8.1 psycopg2-2.6 pytz-2015.4 requests-2.7.0 six-1.9.0 static3-0.6.0 wagtail-0.8.7
==> default: Traceback (most recent call last):
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/conf/__init__.py", line 94, in __init__
==> default:     mod = importlib.import_module(self.SETTINGS_MODULE)
==> default:   File "/usr/local/lib/python3.4/importlib/__init__.py", line 109, in import_module
==> default:     return _bootstrap._gcd_import(name[level:], package, level)
==> default:   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
==> default:   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
==> default:   File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
==> default: ImportError: No module named 'wagtaildemo.settings'
==> default: 
==> default: During handling of the above exception, another exception occurred:
==> default: 
==> default: Traceback (most recent call last):
==> default:   File "/vagrant/manage.py", line 10, in <module>
==> default:     execute_from_command_line(sys.argv)
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
==> default:     utility.execute()
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
==> default:     settings.INSTALLED_APPS
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/conf/__init__.py", line 46, in __getattr__
==> default:     self._setup(name)
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/conf/__init__.py", line 42, in _setup
==> default:     self._wrapped = Settings(settings_module)
==> default:   File "/home/vagrant/.virtualenvs/wagtaildemo/lib/python3.4/site-packages/django/conf/__init__.py", line 98, in __init__
==> default:     % (self.SETTINGS_MODULE, e)
==> default: ImportError: Could not import settings 'wagtaildemo.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named 'wagtaildemo.settings'
```

A `git status` shows the following;

```
$ git st
On branch master
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	deleted:    wagtaildemo/__init__.py
	deleted:    wagtaildemo/heroku_wsgi.py
	deleted:    wagtaildemo/settings/__init__.py
	deleted:    wagtaildemo/settings/base.py
	deleted:    wagtaildemo/settings/dev.py
	deleted:    wagtaildemo/settings/heroku.py
	deleted:    wagtaildemo/settings/local.py.example
	deleted:    wagtaildemo/settings/production.py
	deleted:    wagtaildemo/urls.py
	deleted:    wagtaildemo/wsgi.py

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	__init__.py
	heroku_wsgi.py
	settings/
	urls.py
	wsgi.py
```

Which seems a little odd, I certainly didn't delete them.

A simple (and extremely hacky) fix is to do the following;

```diff
$ git diff Vagrantfile
diff --git a/Vagrantfile b/Vagrantfile
index 8a2473c..f2bca89 100644
--- a/Vagrantfile
+++ b/Vagrantfile
@@ -39,6 +39,8 @@ Vagrant.configure(2) do |config|
   # the path on the guest to mount the folder. And the optional third
   # argument is a set of non-required options.
   # config.vm.synced_folder "../data", "/vagrant_data"
+  config.vm.synced_folder "./", "/vagrant/wagtaildemo"
+  config.vm.synced_folder "settings", "/vagrant/wagtaildemo/settings"
 
   # Provider-specific configuration so you can fine-tune various
   # backing providers for Vagrant. These expose provider-specific options.
```

**Comment by kaedroho** [comment]
What version of Vagrant are you using? (``vagrant --version``)

**Comment by gasman** [comment]
The Getting Started docs no longer cover wagtaildemo/vagrant.
