### ISSUE TITLE
Heroku deployment broken

### ISSUE THREAD

**Issue by casdr** [torchbox/wagtaildemo#88]
The deploy to Heroku button doesn't works:

```
Traceback (most recent call last):
  File "/app/.heroku/python/bin/django-admin.py", line 5, in <module>
    management.execute_from_command_line()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 440, in execute
    self.check()
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/management/base.py", line 478, in check
    include_deployment_checks=include_deployment_checks,
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/app/.heroku/python/lib/python2.7/site-packages/django/core/checks/model_checks.py", line 28, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailcore/models.py", line 572, in check
    if not issubclass(edit_handler.get_form_class(cls), WagtailAdminPageForm):
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 294, in get_form_class
    formsets=cls.required_formsets(),
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 240, in required_formsets
    formsets.update(handler_class.required_formsets())
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 240, in required_formsets
    formsets.update(handler_class.required_formsets())
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 603, in required_formsets
    'widgets': child_edit_handler_class.widget_overrides(),
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 216, in widget_overrides
    widgets.update(handler_class.widget_overrides())
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 216, in widget_overrides
    widgets.update(handler_class.widget_overrides())
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 516, in widget_overrides
    content_type=cls.target_content_type(), can_choose_root=cls.can_choose_root)}
  File "/app/.heroku/python/lib/python2.7/site-packages/wagtail/wagtailadmin/edit_handlers.py", line 543, in target_content_type
    cls._target_content_type = [ContentType.objects.get_for_model(target_model)]
  File "/app/.heroku/python/lib/python2.7/site-packages/django/contrib/contenttypes/models.py", line 78, in get_for_model
    "Error creating new content types. Please make sure contenttypes "
RuntimeError: Error creating new content types. Please make sure contenttypes is migrated before trying to migrate apps individually.
```

**Comment by gasman** [comment]
@casdr Thanks for reporting! This was a regression in Wagtail 1.4.2 - we've just released 1.4.3 which hopefully fixes the issue.
