### ISSUE TITLE
Error on importing html5lib package

### ISSUE THREAD

**Issue by diansheng** [torchbox/wagtaildemo#94]
While I attempt to run demo with the command `./manage.py makemigrations`, i came across import error on html5lib package. Here is my trackback.
```
(wagtail_demo_env) SeanMBP:wagtaildemo sean$ ./manage.py makemigrations
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/wagtaildemo/demo/models.py", line 9, in <module>
    from wagtail.wagtailcore.fields import RichTextField, StreamField
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/wagtail/wagtailcore/fields.py", line 9, in <module>
    from wagtail.wagtailcore.blocks import Block, BlockField, StreamBlock, StreamValue
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/__init__.py", line 5, in <module>
    from .field_block import *  # NOQA
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/wagtail/wagtailcore/blocks/field_block.py", line 15, in <module>
    from wagtail.wagtailcore.rich_text import RichText
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/wagtail/wagtailcore/rich_text.py", line 11, in <module>
    from wagtail.wagtailcore.whitelist import Whitelister
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/wagtail/wagtailcore/whitelist.py", line 9, in <module>
    from bs4 import BeautifulSoup, Comment, NavigableString, Tag
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/Users/diansheng/Codebox/tryout_django/wagtail_demo_env/lib/python2.7/site-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```

And here is all i did.

1. create a virtualenv, activate it.
2. git clone this repo
3. remove psycopg2 in requirement.txt as i will use sqlite
4. pip install -r requirement.txt
5. change database settings in base.py for sqlite
6. ./manage.py makemigrations

**Comment by gasman** [comment]
Hi @diansheng - thanks for the report! This is due to some breaking internal changes in the new version of html5lib released last week: https://github.com/torchbox/wagtail/pull/2842

I've now updated wagtaildemo in fa8c94fa95fbfcb8b74f1afb2ea21719583f5791 to pin html5lib to the old release.

**Comment by diansheng** [comment]
Thanks. I will try again.
